# docker compose -f compose.yml up -d --force-recreate

name: alpine-apache_php
services:
    apache-php_web:
        image: 44934045/alpine-apache_php:armv7
        networks:
            - lamp-net
        volumes:
            - ./html:/var/www/html ##Bind your html folder

        command: sh -c "chown apache:apache /var/www/html ;
                        httpd -D FOREGROUND"
        ports:
            - "80:80"

        depends_on:
            - lamp_db

    lamp_db:
        image: etaylashev/mariadb:armv7-latest
        networks:
            - lamp-net
        volumes:
            #- lamp-db:/var/lib/mysql
            - ./radiodb-init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: zaq123edc
            MYSQL_DATABASE: radio
            MYSQL_USER: radio
            MYSQL_PASSWORD: zaq12wsx
            MYSQL_ROOT_HOST: "%"
            TZ: America/Sao_Paulo #Welcome to BraSil!

volumes:
    lamp-db:

networks:
    lamp-net:
       enable_ipv6: true
